plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\Cristo\\Documents\\WLS ROTERO\\WLS Rotero NUEVA\\WEB\\2711\\ROTERO ANTIGRAVITY"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/tienda"
to = "/tienda.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/tienda/producto/*"
to = "/tienda-producto.html?slug=:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]